build:
#	GOOS=linux GOARCH=amd64 go build
	docker build -t consignment-cli .

run:
	docker run -e MICRO_REGISTRY=mdns \
		--network shippy_default \
		consignment-cli consignment.json \
		4e30c4a3-b280-4525-92b5-34c882d



#		eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyIjp7ImlkIjoiMmRjMmQ0MWMtZjVkNi00NDcxLTllZDgtMGI3N2RlZWZlYjYwIiwibmFtZSI6IlJpY2ggSmFtZXMiLCJjb21wYW55IjoiQmxhY2sgRG9nIENvbXBhbnkgTExDIiwiZW1haWwiOiJyaWNoamFtZXNwdWIxQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJFdwbnBTUnI1QjVzSFZscGJvNkpmOWVudGFPTWhRcEUvZ3Z2VGJZUExnMDFiM1h3TzNoUTJHIn0sImV4cCI6MTU3ODQxNDI2NiwiaXNzIjoidXNlci5zcnYifQ.nrh9_azDi3mg2LWhk-QPI04CFVx9iaBq9M8F7IPEHCQ

#		4e30c4a3-b280-4525-92b5-34c882d
